version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           wget https://raw.githubusercontent.com/AnGgIt86/NFSKernel-interface/main/rosy/nfs/source.sh
           bash source.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
    - compile
