version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   environment:
      GIT_EMAIL: jarbull86@gmail.com
      GIT_NAME: AnGgIt86
      VERSION: 2.2
   steps:
      - run:
          command: |
           dpkg-reconfigure --frontend noninteractive tzdata
           curl https://raw.githubusercontent.com/AnGgIt86/NFSKernel-compiler/master/kernel_build.sh -o kernel_build.sh
           source ./kernel_build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
