version: 2.1
jobs:
  build:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           wget https://raw.githubusercontent.com/AnGgIt86/NFSKernel-interface/main/rosy/overclock/source.sh
           bash source.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
    - build
